# Notebook Imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [84]:
TRAINING_DATA_FILE = 'SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'SpamData/02_Training/test-data.txt'

TOKEN_SPAM_PROB_FILE = 'SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURE_MATRIX = 'SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'SpamData/03_Testing/test-target.txt'


VOCAB_SIZE = 2500

# Read and Load Features from .txt files into NumPy Array

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ', dtype=int)

In [4]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ', dtype=int)

In [5]:
sparse_train_data[:5]

array([[ 0,  0,  1,  2],
       [ 0,  7,  1,  1],
       [ 0, 16,  1,  1],
       [ 0, 18,  1,  1],
       [ 0, 24,  1,  1]])

In [6]:
sparse_train_data[-5:]

array([[5795, 1846,    0,    1],
       [5795, 1899,    0,    2],
       [5795, 2112,    0,    1],
       [5795, 2276,    0,    1],
       [5795, 2478,    0,    1]])

In [7]:
print('Nr of rows in training file', sparse_train_data.shape[0])
print('Nr of rows in test file', sparse_test_data.shape[0])

Nr of rows in training file 265567
Nr of rows in test file 110581


In [8]:
print('Nr of emails in training file', np.unique(sparse_train_data[:, 0]).size)

Nr of emails in training file 4014


In [9]:
print('Nr of emails in test file', np.unique(sparse_test_data[:, 0]).size)

Nr of emails in test file 1723


# How to create an Empty DataFrame

In [10]:
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [11]:
index_names = np.unique(sparse_train_data[:, 0])
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [12]:
full_train_data = pd.DataFrame(index=index_names, columns=column_names)
full_train_data.fillna(value=0)

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...      ...       ... .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5789       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5790       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5791       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5794       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5795       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
5789     0     0     0     0     0     0  
5790     0     0     0     0     0     0  
5791     0     0     0     0     0     0  
5794     0     0     0     0     0     0  
5795     0     0     0     0     0     0  

[4014 rows x 2502 columns]

In [13]:
full_train_data.head()

DOC_ID CATEGORY    0    1    2    3    4    5    6    7  ... 2490 2491 2492  \
0    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
3    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
4    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   

  2493 2494 2495 2496 2497 2498 2499  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 2502 columns]

# Create a Full Matrix from a Sparse Matrix

In [14]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    """
    From a full matrix from a sparse matrix. Returns a pandas dataframe.
    Keyword arguements:
    sparse_matrix -- numpy array
    nr_words -- size of the vocabulary. Total number of tokens.
    doc_idx -- position of the document id in the sparse matrix. Default: 1st column
    word_idx -- position of the word id in the sparse matrix. Default: 2nd column
    cat_idx -- position of the label (spam is 1, nonspam is 0). Default: 3rd column
    freq_idx -- position of occurrence of word in sparse matrix. Default: 4th column  
    """
    
    column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, nr_words))
    doc_id_names = np.unique(sparse_matrix[:, 0])
    full_matrix = pd.DataFrame(index=doc_id_names, columns=column_names)
    full_matrix.fillna(value=0, inplace=True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_nr = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurrence = sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_nr, 'DOC_ID'] = doc_nr
        full_matrix.at[doc_nr, 'CATEGORY'] = label
        full_matrix.at[doc_nr, word_id] = occurrence
        
         
        
    full_matrix.set_index('DOC_ID', inplace=True)
    return full_matrix

    
    

In [15]:
%%time 
full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)

CPU times: user 9.1 s, sys: 146 ms, total: 9.24 s
Wall time: 9.47 s


In [16]:
full_train_data.tail()

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
5789           0  0  0  0  0  0  5  0  0  0  ...     0     0     0     0   
5790           0  2  2  1  0  0  0  1  0  1  ...     0     0     0     0   
5791           0  2  0  1  1  0  1  2  0  1  ...     0     0     0     0   
5794           0  2  2  1  0  1  1  1  0  1  ...     0     0     0     0   
5795           0  1  1  1  0  1  1  0  0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
5789       0     0     0     0     0     0  
5790       0     0     0     0     0     0  
5791       0     0     0     0     0     0  
5794       0     0     0     0     0     0  
5795       0     0     0     0     0     0  

[5 rows x 2501 columns]

# Training with Naive Bayes Model

## Calculating the Probability of Spam

In [27]:
# Probability of Spam
prob_spam = full_train_data.CATEGORY.value_counts()[1]/full_train_data.CATEGORY.size
print('Probability of spam is ', prob_spam)

Probability of spam is  0.3111609367214748


# Total Number of Words / Tokens

In [28]:
full_train_features = full_train_data.loc[:, full_train_data.columns != 'CATEGORY']
full_train_features.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          2     0     0     0     0     0     0     1     0     0  ...     0   
1          2     0     1     2     1     1     0     0     0     0  ...     0   
2          2     0     2     0     0     3     0     0     0     0  ...     0   
3          3     0     0     1     0     1     1     0     0     0  ...     0   
4          0     0     0     1     2     4     2     3     1     1  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [33]:
email_lengths = full_train_features.sum(axis=1)

In [35]:
total_wc = email_lengths.sum()
total_wc

444962

##  Number of Tokens in Spam & Ham Emails

In [56]:
spam_lengths = email_lengths[full_train_data.CATEGORY == 1]
spam_wc = spam_lengths.sum()


In [75]:
ham_lengths = email_lengths[full_train_data.CATEGORY == 0]
ham_wc = ham_lengths.sum()
ham_lengths.shape

(2765,)

In [76]:
email_lengths.shape[0] - spam_lengths.shape[0] - ham_lengths.shape[0]

0

In [77]:
print('Average nr of words in spam emails {:.0f}'.format(spam_wc / spam_lengths.shape[0]))
print('Average nr of words in ham emails {:.0f}'.format(ham_wc / ham_lengths.shape[0]))

Average nr of words in spam emails 155
Average nr of words in ham emails 91


# Summing the Tokens Occuring in Spam

In [63]:
full_train_features.shape

(4014, 2500)

In [64]:
train_spam_tokens = full_train_features.loc[full_train_data.CATEGORY == 1]
train_spam_tokens.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          2     0     0     0     0     0     0     1     0     0  ...     0   
1          2     0     1     2     1     1     0     0     0     0  ...     0   
2          2     0     2     0     0     3     0     0     0     0  ...     0   
3          3     0     0     1     0     1     1     0     0     0  ...     0   
4          0     0     0     1     2     4     2     3     1     1  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [65]:
train_spam_tokens.shape

(1249, 2500)

In [67]:
summed_spam_tokens = train_spam_tokens.sum(axis=0) + 1
summed_spam_tokens.shape

(2500,)

In [68]:
summed_spam_tokens.tail()

2495    17
2496    26
2497     7
2498    10
2499    17
dtype: int64

In [69]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1
summed_ham_tokens.shape

(2500,)

## P(Token | Spam) - Probability that a Token Occurs given the Email is Spam

In [71]:
prob_tokens_spam = summed_spam_tokens / (spam_wc + VOCAB_SIZE)

In [72]:
prob_tokens_spam.sum()

0.9999999999999999

# P(Token | Ham) - Probability that a Token Occurs given the Email is Nonspam


In [79]:
prob_tokens_nonspam = summed_ham_tokens / (ham_wc + VOCAB_SIZE)
prob_tokens_nonspam.sum()

1.0

# P(Token) - Probability that Token Occurs

In [80]:
prob_tokens_all = full_train_features.sum(axis=0) / total_wc

In [81]:
prob_tokens_all.sum()

1.0

# Save the Trained Model

In [83]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_nonspam)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)

# Prepare Test Data

In [89]:
%%time
full_test_data = make_full_matrix(sparse_test_data, VOCAB_SIZE)

CPU times: user 3.7 s, sys: 32.3 ms, total: 3.74 s
Wall time: 3.74 s


In [90]:
X_test = full_test_data.loc[:, full_test_data.columns != 'CATEGORY']
y_test = full_test_data.CATEGORY

In [91]:
np.savetxt(TEST_TARGET_FILE, y_test)
np.savetxt(TEST_FEATURE_MATRIX, X_test)